version: "3.1"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/src
      - /src/node_modules
    depends_on:
      - mysql_server
  mysql_server:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      - MYSQL_DATABASE=articles_info
      - MYSQL_USER=test123
      - MYSQL_PASSWORD=test123
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306